In [1]:
import numpy as np

In [2]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((2,4)) # Notice that it is a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3,4)) # Notice that is is a tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# linspace takes in the number of points you want
np.linspace(0,5,10) # start at 0, end at 5, 10 evenly spaced points
# it looks 2d but is only 1d because of the number of brackets

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
# Identiy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
# Creating arrays of random numbers

# rand creates an array of the space you pass in and populate it with random
# samples from a uniform distribution from 0 to 1
np.random.rand(5) # 1d

array([0.40130848, 0.51928982, 0.02526048, 0.45023329, 0.31931755])

In [10]:
np.random.rand(5,5) # Notice that we don't need to pass in a tuple this time

array([[0.04621909, 0.65987781, 0.24231084, 0.56326239, 0.22245157],
       [0.35462317, 0.32086011, 0.30215051, 0.85563868, 0.40281572],
       [0.88562381, 0.41555619, 0.36131028, 0.09959981, 0.83410885],
       [0.99750143, 0.17250651, 0.10643245, 0.37913024, 0.76596915],
       [0.52871484, 0.20467989, 0.53354276, 0.67700527, 0.79726092]])

In [12]:
# randn returns from a normal distribution (Gaussian) centered at 0
np.random.randn(2)

array([0.8138791 , 0.12027417])

In [13]:
np.random.randn(3,3)

array([[ 0.03150734,  0.90830926,  0.51870937],
       [-1.31933066, -0.55751014,  0.07845749],
       [-1.22245273, -0.32545448, -0.51581022]])

In [14]:
# randint returns random integers from a low to a high number
# low is inclusice, high is not

np.random.randint(1,100)

18

In [15]:
# third arguement can be a number of random numbers you want

np.random.randint(1,100,5)

array([69, 53, 64, 55, 53])

In [16]:
# Some array practice examples and useful information

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
ranarr = np.random.randint(0,50,10)

In [20]:
ranarr

array([40, 19, 44, 30, 46,  2,  2, 48, 12, 47])

In [21]:
# You can reshape arrays into new shapes
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
# Find the max value
ranarr.max()

48

In [23]:
# Find the min value
ranarr.min()

2

In [24]:
# To know the index location of the maximum value:
ranarr.argmax()

7

In [25]:
# To know the index location of the minimum value:
ranarr.argmin() # Notice is only grabs the first min

5

In [26]:
# Tells us the shape of the array. 
# This output tells us that it doesn't have a second dimension
arr.shape

(25,)

In [27]:
arr2 = arr.reshape(5,5)
arr2.shape

(5, 5)

In [28]:
# To know the type of the data in the array
arr.dtype

dtype('int32')

### Numpy Indexing and Selection

In [29]:
arr = np.arange(0,11)

In [30]:
# To get a single value
arr[8] # returns the value at the 8th index

8

In [31]:
# To get a range of values
arr[1:5] # start at index 1 and go up to but not incldue index 5 

array([1, 2, 3, 4])

In [33]:
# Include everything up to an index:
arr[:6] # same as arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [34]:
# start at a prticular index and go to the end of the array
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
# numpy allows us to broadcast
arr[0:5] = 100

In [36]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [37]:
# you have to be careful when doing this because 
# numpy does not actual copy values to avoid memory issues
# with large arrays. 
arr = np.arange(0,11)
slice_of_arr = arr[0:6]

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [41]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [42]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
# Notice that changing the values in slice_of_arr also changed 
# the values of arr. 
# Numpy only provides a view of arrays, not copies

In [44]:
# To get a copy
arr_copy = arr.copy()

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr_copy[:] = 100

In [48]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2d arrays, matrices

In [50]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [51]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
# There are a couple ways to grab elements from 2d arrays

5

In [54]:
arr_2d[0][0] # [row][column]

5

In [55]:
arr_2d[0,0] # [row, column]
# This is the recommended way

5

In [56]:
arr_2d[1] # returns the second row

array([20, 25, 30])

In [57]:
# Say you want to grab a sub-matrix 
arr_2d[:2, 1:] 
# grab rows index up to but not including index 2
# grabs columns starting at index 1

array([[10, 15],
       [25, 30]])

In [58]:
# Conditional Selection

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
bool_arr = arr > 5
# Returns a boolean array

In [64]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [66]:
arr[bool_arr] # we only get the values that evaluate to True

array([ 6,  7,  8,  9, 10])

In [67]:
# normally written like this
arr[arr>5]

array([ 6,  7,  8,  9, 10])

# Numpy Operations

In [68]:
arr = np.arange(0,11)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr + arr # Adds the elements of the arrays together

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [75]:
arr + 100 # numpy broadcasts this to every element

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [76]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [77]:
# Sometimes Numpy will give you a warning instead of an error
# Dividing by 0 normally gives an error
1/0

ZeroDivisionError: division by zero

In [78]:
# but Numpy will return a warning
# first element is 0
arr / arr

C:\Users\Jared\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [79]:
1 / arr # gives infinity

C:\Users\Jared\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [80]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])